config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'notifications/index'
    get 'notifications/destroy'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  
}
  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only:[:index, :show, :edit, :update]
    get 'search' => 'searches#search'
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get 'search' => 'searches#search'
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :favorites
      get 'unsubscribe'
      patch 'withdraw'
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:index, :create, :destroy] 
      resources :comments, only: [:create, :destroy]
    end
    resources :reports, only: [:new, :create] 
    resources :notifications, only: [:index, :destroy]
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/followed.rb
class Followed < ApplicationRecord
end

app/models/follower.rb
class Follower < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  
  has_one_attached :post_image
  
  validates :body, presence: true
  validates :post_image, presence: true
  
  def save_tags(tag_ids)
  # タグIDがnilの場合（チェックボックスが選択されなかった場合）、
  # 関連付けられているタグを全て削除します。
    return tags.clear if tag_ids.nil?

    current_tags = tags.pluck(:id)
    new_tags = tag_ids.map(&:to_i) - current_tags
    old_tags = current_tags - tag_ids.map(&:to_i)

    old_tags.each do |old_tag_id|
      tags.delete(Tag.find(old_tag_id))
    end

    new_tags.each do |new_tag_id|
      tag = Tag.find(new_tag_id)
      tags << tag unless tags.include?(tag)
    end
  end



  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("body LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("body LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end
  
  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      post_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
    
  def follow(user_id)
    followers.create(followed_id: user_id)
  end

  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end	 
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  
  validates :name, uniqueness: true, presence: true, length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.nickname = "げすと"
      user.is_deleted = false
    end
  end
  
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  
  has_one_attached :header_image
  has_one_attached :icon_image
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  
  def get_header_image(width, height)
    unless header_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      header_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      header_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_icon_image(width, height)
    unless icon_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      icon_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      icon_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # 特定のユーザーがこのユーザーをフォローしているかどうかを確認
  def following?(other_user)
    self.following_users.include?(other_user)
  end
  
  # 他のユーザーをフォロー
  def follow(other_user_id)
    followers.create(followed_id: other_user_id)
  end

  # フォローを解除
  def unfollow(other_user_id)
    followers.find_by(followed_id: other_user_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search
  
  def search
    @q = Post.ransack(params[:q])
    @post = @q.result(distinct: true)
    @result = params[:q]&.values&.reject(&blank?)
  end

  protected
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when User
      root_path
    else
      super # Deviseのデフォルトの挙動を呼び出す
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    elsif resource_or_scope == :user
      new_user_session_path
    else
      root_path # または他のデフォルトのパス
    end
  end

  
  def guest_sign_in
    user = User.guest
    sign_in user
    flash[:notice] = "ゲストユーザーとしてログインしました。"
    redirect_to root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :nickname, :phone_number, :is_deleted, :is_user_status, :encrypted_password])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_item(name, path, options = {})
    class_name = 'channel'
    class_name << ' active' if current_page?(path)

    content_tag :li, class:class_name do
      link_to name, path, options
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<br><br><br>

<footer>
  <div class="container">
    <div class="small text-center text-muted" style="margin: 50px 0;">
      CopyRight @ Petter
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">

    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <div class="row-100">
          <div class="col-4">
            <a href="https://dd395bbb0a2244cf9630f0e758761021.vfs.cloud9.ap-southeast-2.amazonaws.com/" class="navbar-brand">
              <div="border p-2">
                PETTER
              </div>
            </a>
          </div>
    <div class="col-8 text-right">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" 
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    
      <ul class="navbar-nav ml-auto">
        
        <% if user_signed_in? %>
        
          <li class="nav-item" style="margin-right:40px;">
            <% flash.each do |key, message| %>
              <div class="flash <%= key %>"><%= message %></div>
            <% end %>
          </li>
        
          <li class="nav-item" style="margin-right:40px;">
            ようこそ、<%= current_user.name %>さん!
          </li>
          
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to root_path, style: "color:black;" do %>
              <i class="fas fa-home" aria-hidden="true"></i>
            <% end %>
          </li>
          
          <li class="nav-item" style="margin-right:20px;">
            <% if @user.present? %>
              <%= link_to user_path(@user.id), style: "color:black;" do %>
                <i class="fa-solid fa-user" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </li>
          
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to new_post_path, style: "color:black;" do %>
              <i class="fa-solid fa-plus" aria-hidden="true"></i>
            <% end %>
          </li>
          
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to favorites_user_path(current_user), style: "color:black;" do %>
              <i class="fa-solid fa-heart" aria-hidden="true"></i>
            <% end %>
          </li>
          
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to about_path, style: "color:black;" do %>
              <i class="fa-solid fa-link" aria-hidden="true"></i>
            <% end %>
          </li>
         
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to destroy_user_session_path, method: :delete, style: "color:black;" do %>
              <i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i>
            <% end %>
          </li>
          
            <%= render "layouts/search" %>
          
        <% else %>
        
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to "トップページ", root_path, style: "color:black;" %>
          </li>
         
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to "新規登録", new_user_registration_path, style: "color:black;" %>
          </li>
         
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to "ログイン", new_user_session_path, style: "color:black;" %>
          </li>
         
          <li class="nav-item" style="margin-right:20px;">
            <%= link_to "About", about_path, style: "color:black;" %>
            </li>
            
        <% end %>

        </ul>
      </div>
      </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'],['Post']]) %>
      <%= f.select :search, options_for_select([["完全一致","Perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class:"btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="listings">
  <div class="listings_channels">
    <h2 class="listings_header">admin</h2>
    <ul class="channel_list">
      <% if admin_signed_in? %>
        <%= sidebar_link_item "トップ", admin_path %>
        <% if current_user %>
          <%= sidebar_link_item "エディット", edit_admin_user_path(current_user) %>
        <% end %>
        <%= sidebar_link_item "ログアウト", destroy_admin_session_path, method: :delete %>
      <% else %>
        <%= sidebar_link_item "ログイン", new_admin_session_path %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/83484975db.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <% if user_signed_in? %>
    
      <body id="wrapper" style="background-color: white;">
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        
        <div class="row">
          <div class="col-2">
            <%= render "layouts/sidebar" %>
          </div>
        </div>
        
        <div class="container">
          <%= yield %>
        </div>
        
        <%= render "layouts/footer" %>
      </body>
      
    <% elsif admin_signed_in? %>
    
      <body id="wrapper" style="background-color: #EEEEEE;">
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        
        <div class="row">
          <div class="col-2">
            <%= render "layouts/sidebar" %>
          </div>
        </div>
          
        <div class="container">
          <%= yield %>
        </div>
        
        <%= render "layouts/footer" %>
      </body>
      
    <% else %>
    
      <body id="wrapper" style="background=color: white;">
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        
        <div class="row">
          <div class="col-2">
            <%= render "layouts/sidebar" %>
          </div>
        </div>
        
        <div class="container">
          <%= yield %>
        </div>
        
        <%= render "layouts/footer" %>
      </body>
      
    <% end %>

</html>